"use client";

import { useState, useTransition } from "react";
import {
  Sparkles,
  RefreshCw,
  Play,
  CheckCircle2,
  AlertCircle,
  ExternalLink,
  Lock,
  ShieldCheck,
  Clock,
  Sliders,
  Globe,
  FileText,
  Radio,
  Tv,
  Gamepad2,
  X,
  Send,
  Eye,
  Check,
  Layers,
  Zap,
  ArrowRight,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import {
  testApiConnectionAction,
  runPandaScoreSyncAction,
  generateAiBlogAction,
  publishDraftBlogAction,
  triggerCronAction,
} from "@/app/(dashboard)/actions/ingestion-actions";
import Link from "next/link";

export function IngestionClient({ initialData, userRole }) {
  const [data, setData] = useState(initialData || {});
  const [isPending, startTransition] = useTransition();
  const [statusMessage, setStatusMessage] = useState(null);
  const [activeTab, setActiveTab] = useState("rss_ai"); // rss_ai | pandascore | cron_jobs | audit

  // API Health state
  const [apiTesting, setApiTesting] = useState({});
  const [apiResults, setApiResults] = useState({});

  // PandaScore Form State
  const [selectedGame, setSelectedGame] = useState("valorant");
  const [syncLimit, setSyncLimit] = useState(10);
  const [dryRun, setDryRun] = useState(true);
  const [syncResult, setSyncResult] = useState(null);

  // Custom AI Generation Form State
  const [customTopic, setCustomTopic] = useState("");
  const [selectedCategory, setSelectedCategory] = useState("news");
  const [autoPublish, setAutoPublish] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);

  // Draft Review Modal
  const [draftModal, setDraftModal] = useState(null);

  const dbMetrics = data.dbMetrics || {};
  const rssItems = data.rssItems || [];
  const history = data.history || [];
  const recentBlogs = data.recentBlogs || [];

  const handleTestApi = async (apiName) => {
    setApiTesting((prev) => ({ ...prev, [apiName]: true }));
    try {
      const res = await testApiConnectionAction(apiName);
      setApiResults((prev) => ({
        ...prev,
        [apiName]: res,
      }));
      if (res.success) {
        setStatusMessage({
          type: "success",
          text: `[${apiName.toUpperCase()}] ${res.details} (${res.latency}ms)`,
        });
      } else {
        setStatusMessage({
          type: "error",
          text: `[${apiName.toUpperCase()} Error] ${res.error}`,
        });
      }
    } catch (err) {
      setStatusMessage({ type: "error", text: `Connection test failed: ${err.message}` });
    } finally {
      setApiTesting((prev) => ({ ...prev, [apiName]: false }));
      setTimeout(() => setStatusMessage(null), 5000);
    }
  };

  const handleRunPandaScore = () => {
    startTransition(async () => {
      setSyncResult(null);
      const res = await runPandaScoreSyncAction({
        gameSlug: selectedGame,
        limit: Number(syncLimit),
        dryRun,
      });

      if (res.success) {
        setSyncResult(res);
        setStatusMessage({
          type: "success",
          text: res.message || "PandaScore sync complete.",
        });
      } else {
        setStatusMessage({
          type: "error",
          text: res.error || "PandaScore sync failed.",
        });
      }
      setTimeout(() => setStatusMessage(null), 6000);
    });
  };

  const handleGenerateFromRss = (item) => {
    setIsGenerating(true);
    startTransition(async () => {
      const res = await generateAiBlogAction({
        sourceTitle: item.title,
        sourceSnippet: item.contentSnippet,
        sourceLink: item.link,
        category: "news",
        autoPublish: false, // always review draft
      });

      setIsGenerating(false);

      if (res.success) {
        setDraftModal(res.draft);
        setStatusMessage({
          type: "success",
          text: `Article draft generated by Gemini 2.5 Flash! Please review below before publishing.`,
        });
      } else {
        setStatusMessage({
          type: "error",
          text: res.error || "Failed to generate AI article.",
        });
      }
      setTimeout(() => setStatusMessage(null), 5000);
    });
  };

  const handleGenerateCustom = () => {
    if (!customTopic.trim()) {
      setStatusMessage({ type: "error", text: "Please enter a topic headline." });
      return;
    }

    setIsGenerating(true);
    startTransition(async () => {
      const res = await generateAiBlogAction({
        customTopic,
        category: selectedCategory,
        autoPublish,
      });

      setIsGenerating(false);

      if (res.success) {
        if (res.published) {
          setStatusMessage({
            type: "success",
            text: `Article published live: '${res.blog?.title}'`,
          });
          setCustomTopic("");
        } else {
          setDraftModal(res.draft);
          setStatusMessage({
            type: "success",
            text: `Draft generated! Review content below before publishing.`,
          });
        }
      } else {
        setStatusMessage({
          type: "error",
          text: res.error || "Generation failed.",
        });
      }
      setTimeout(() => setStatusMessage(null), 6000);
    });
  };

  const handlePublishDraft = () => {
    if (!draftModal) return;

    startTransition(async () => {
      const res = await publishDraftBlogAction(draftModal);
      if (res.success) {
        setStatusMessage({
          type: "success",
          text: `Draft published live to KhelPediA! (ID: ${res.blog?.id})`,
        });
        setDraftModal(null);
      } else {
        setStatusMessage({
          type: "error",
          text: res.error || "Failed to publish draft.",
        });
      }
      setTimeout(() => setStatusMessage(null), 6000);
    });
  };

  const handleTriggerCron = () => {
    startTransition(async () => {
      const res = await triggerCronAction();
      if (res.success) {
        setStatusMessage({
          type: "success",
          text: res.message || "Cron job executed successfully.",
        });
      } else {
        setStatusMessage({
          type: "error",
          text: res.error || "Cron trigger failed.",
        });
      }
      setTimeout(() => setStatusMessage(null), 6000);
    });
  };

  return (
    <div className="space-y-6">
      {/* Top Header Card */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 p-6 rounded-xl bg-gradient-to-r from-zinc-900 via-zinc-900/90 to-zinc-950 border border-zinc-800 shadow-xl">
        <div className="space-y-1">
          <div className="flex items-center gap-2.5">
            <div className="h-9 w-9 rounded-lg bg-indigo-500/10 border border-indigo-500/20 flex items-center justify-center text-indigo-400 shadow-sm">
              <Sparkles className="h-5 w-5" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h1 className="text-xl font-bold text-white tracking-tight">
                  Data Ingestion & AI Automation
                </h1>
                <Badge
                  variant="outline"
                  className="bg-emerald-500/10 text-emerald-400 border-emerald-500/20 text-[10px] font-mono flex items-center gap-1"
                >
                  <Lock className="h-2.5 w-2.5" />
                  Private Network Only (Port 3001)
                </Badge>
              </div>
              <p className="text-xs text-zinc-400">
                PandaScore match sync, Gemini 2.5 Flash editorial journalism, VLR.gg news feeds, and background cron schedules.
              </p>
            </div>
          </div>
        </div>

        {/* Global Action Buttons */}
        <div className="flex items-center gap-2.5">
          <Button
            variant="outline"
            size="sm"
            onClick={handleTriggerCron}
            disabled={isPending || isGenerating}
            className="border-zinc-700 bg-zinc-800/80 hover:bg-zinc-700 text-zinc-200 text-xs gap-1.5"
          >
            <Play className={`h-3 w-3 ${isPending ? "animate-spin" : ""}`} />
            Run Hourly Cron
          </Button>

          <Button
            size="sm"
            onClick={() => setActiveTab("rss_ai")}
            className="bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-semibold gap-1.5 shadow-sm"
          >
            <Sparkles className="h-3.5 w-3.5" />
            AI Writer Hub
          </Button>
        </div>
      </div>

      {/* Status Alert Banner */}
      {statusMessage && (
        <div
          className={`flex items-center gap-2 p-3.5 rounded-lg border text-xs font-medium transition-all ${
            statusMessage.type === "success"
              ? "bg-emerald-500/10 text-emerald-400 border-emerald-500/20"
              : "bg-red-500/10 text-red-400 border-red-500/20"
          }`}
        >
          {statusMessage.type === "success" ? (
            <CheckCircle2 className="h-4 w-4 shrink-0" />
          ) : (
            <AlertCircle className="h-4 w-4 shrink-0" />
          )}
          <span>{statusMessage.text}</span>
        </div>
      )}

      {/* External Service Connectivity Status Grid */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        {/* PandaScore */}
        <Card className="bg-zinc-900/60 border-zinc-800">
          <CardHeader className="p-4 pb-2 flex flex-row items-center justify-between space-y-0">
            <span className="text-[11px] font-mono uppercase tracking-wider text-zinc-400">
              PandaScore Esports API
            </span>
            <span className="h-2 w-2 rounded-full bg-emerald-500 animate-pulse" />
          </CardHeader>
          <CardContent className="p-4 pt-1 space-y-2">
            <div className="flex items-center justify-between">
              <span className="text-sm font-semibold text-white">Live Data Feed</span>
              <Badge variant="outline" className="bg-emerald-500/10 text-emerald-400 border-emerald-500/20 text-[9px] font-mono">
                200 OK
              </Badge>
            </div>
            <p className="text-[11px] text-zinc-400">
              {apiResults.pandascore?.details || "Tournaments, matches, and team rosters"}
            </p>
            <div className="pt-2 border-t border-zinc-800/80 flex items-center justify-between">
              <span className="text-[10px] text-zinc-500 font-mono">
                {apiResults.pandascore?.latency ? `${apiResults.pandascore.latency}ms` : "Active Token"}
              </span>
              <Button
                variant="ghost"
                size="sm"
                onClick={() => handleTestApi("pandascore")}
                disabled={apiTesting.pandascore}
                className="h-6 text-[10px] px-2 text-zinc-300 hover:text-white hover:bg-zinc-800 gap-1"
              >
                <RefreshCw className={`h-2.5 w-2.5 ${apiTesting.pandascore ? "animate-spin" : ""}`} />
                Test API
              </Button>
            </div>
          </CardContent>
        </Card>

        {/* Gemini AI */}
        <Card className="bg-zinc-900/60 border-zinc-800">
          <CardHeader className="p-4 pb-2 flex flex-row items-center justify-between space-y-0">
            <span className="text-[11px] font-mono uppercase tracking-wider text-zinc-400">
              Google Gemini AI
            </span>
            <span className="h-2 w-2 rounded-full bg-emerald-500" />
          </CardHeader>
          <CardContent className="p-4 pt-1 space-y-2">
            <div className="flex items-center justify-between">
              <span className="text-sm font-semibold text-white">gemini-2.5-flash</span>
              <Badge variant="outline" className="bg-purple-500/10 text-purple-400 border-purple-500/20 text-[9px] font-mono">
                Ready
              </Badge>
            </div>
            <p className="text-[11px] text-zinc-400">
              {apiResults.gemini?.details || "Automated esports editorial synthesis"}
            </p>
            <div className="pt-2 border-t border-zinc-800/80 flex items-center justify-between">
              <span className="text-[10px] text-zinc-500 font-mono">
                {apiResults.gemini?.latency ? `${apiResults.gemini.latency}ms` : "Key Verified"}
              </span>
              <Button
                variant="ghost"
                size="sm"
                onClick={() => handleTestApi("gemini")}
                disabled={apiTesting.gemini}
                className="h-6 text-[10px] px-2 text-zinc-300 hover:text-white hover:bg-zinc-800 gap-1"
              >
                <RefreshCw className={`h-2.5 w-2.5 ${apiTesting.gemini ? "animate-spin" : ""}`} />
                Test Prompt
              </Button>
            </div>
          </CardContent>
        </Card>

        {/* VLR.gg RSS */}
        <Card className="bg-zinc-900/60 border-zinc-800">
          <CardHeader className="p-4 pb-2 flex flex-row items-center justify-between space-y-0">
            <span className="text-[11px] font-mono uppercase tracking-wider text-zinc-400">
              VLR.gg Esports RSS
            </span>
            <span className="h-2 w-2 rounded-full bg-emerald-500" />
          </CardHeader>
          <CardContent className="p-4 pt-1 space-y-2">
            <div className="flex items-center justify-between">
              <span className="text-sm font-semibold text-white">{rssItems.length} Stories</span>
              <Badge variant="outline" className="bg-blue-500/10 text-blue-400 border-blue-500/20 text-[9px] font-mono">
                Live Feed
              </Badge>
            </div>
            <p className="text-[11px] text-zinc-400">
              {data.rssError ? `Error: ${data.rssError}` : "Source feed for automated articles"}
            </p>
            <div className="pt-2 border-t border-zinc-800/80 flex items-center justify-between">
              <span className="text-[10px] text-zinc-500 font-mono">Polls Hourly</span>
              <Button
                variant="ghost"
                size="sm"
                onClick={() => handleTestApi("rss")}
                disabled={apiTesting.rss}
                className="h-6 text-[10px] px-2 text-zinc-300 hover:text-white hover:bg-zinc-800 gap-1"
              >
                <RefreshCw className={`h-2.5 w-2.5 ${apiTesting.rss ? "animate-spin" : ""}`} />
                Refresh
              </Button>
            </div>
          </CardContent>
        </Card>

        {/* Discord Webhook */}
        <Card className="bg-zinc-900/60 border-zinc-800">
          <CardHeader className="p-4 pb-2 flex flex-row items-center justify-between space-y-0">
            <span className="text-[11px] font-mono uppercase tracking-wider text-zinc-400">
              Discord Webhook
            </span>
            <span className="h-2 w-2 rounded-full bg-emerald-500" />
          </CardHeader>
          <CardContent className="p-4 pt-1 space-y-2">
            <div className="flex items-center justify-between">
              <span className="text-sm font-semibold text-white">Editorial Alert Bot</span>
              <Badge variant="outline" className="bg-indigo-500/10 text-indigo-400 border-indigo-500/20 text-[9px] font-mono">
                Ready
              </Badge>
            </div>
            <p className="text-[11px] text-zinc-400">
              Instant alerts on newly generated articles
            </p>
            <div className="pt-2 border-t border-zinc-800/80 flex items-center justify-between">
              <span className="text-[10px] text-zinc-500 font-mono">Target Channel</span>
              <Button
                variant="ghost"
                size="sm"
                onClick={() => handleTestApi("discord")}
                disabled={apiTesting.discord}
                className="h-6 text-[10px] px-2 text-zinc-300 hover:text-white hover:bg-zinc-800 gap-1"
              >
                <Send className={`h-2.5 w-2.5 ${apiTesting.discord ? "animate-spin" : ""}`} />
                Send Ping
              </Button>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Database Entity Scale Status */}
      <div className="grid grid-cols-2 sm:grid-cols-5 gap-3 p-4 rounded-xl bg-zinc-950/80 border border-zinc-800">
        <div className="space-y-0.5">
          <span className="text-[10px] uppercase font-mono text-zinc-500">Live Matches</span>
          <p className="text-base font-bold text-white">{(dbMetrics.matches || 0).toLocaleString()}</p>
        </div>
        <div className="space-y-0.5">
          <span className="text-[10px] uppercase font-mono text-zinc-500">Tournaments</span>
          <p className="text-base font-bold text-white">{(dbMetrics.tournaments || 0).toLocaleString()}</p>
        </div>
        <div className="space-y-0.5">
          <span className="text-[10px] uppercase font-mono text-zinc-500">Teams Ingested</span>
          <p className="text-base font-bold text-white">{(dbMetrics.teams || 0).toLocaleString()}</p>
        </div>
        <div className="space-y-0.5">
          <span className="text-[10px] uppercase font-mono text-zinc-500">Player Profiles</span>
          <p className="text-base font-bold text-white">{(dbMetrics.players || 0).toLocaleString()}</p>
        </div>
        <div className="space-y-0.5">
          <span className="text-[10px] uppercase font-mono text-zinc-500">Published Blogs</span>
          <p className="text-base font-bold text-emerald-400">{(dbMetrics.blogs || 0).toLocaleString()}</p>
        </div>
      </div>

      {/* Tab Navigation */}
      <div className="flex items-center gap-2 border-b border-zinc-800 pb-2">
        <button
          onClick={() => setActiveTab("rss_ai")}
          className={`px-3.5 py-1.5 rounded-lg text-xs font-medium transition-colors flex items-center gap-2 ${
            activeTab === "rss_ai"
              ? "bg-zinc-800 text-white font-semibold shadow-sm"
              : "text-zinc-400 hover:text-zinc-200 hover:bg-zinc-900"
          }`}
        >
          <Sparkles className="h-3.5 w-3.5 text-indigo-400" />
          <span>AI Editorial & RSS News ({rssItems.length})</span>
        </button>
        <button
          onClick={() => setActiveTab("pandascore")}
          className={`px-3.5 py-1.5 rounded-lg text-xs font-medium transition-colors flex items-center gap-2 ${
            activeTab === "pandascore"
              ? "bg-zinc-800 text-white font-semibold shadow-sm"
              : "text-zinc-400 hover:text-zinc-200 hover:bg-zinc-900"
          }`}
        >
          <Gamepad2 className="h-3.5 w-3.5 text-amber-400" />
          <span>PandaScore Match Ingestion</span>
        </button>
        <button
          onClick={() => setActiveTab("cron_jobs")}
          className={`px-3.5 py-1.5 rounded-lg text-xs font-medium transition-colors flex items-center gap-2 ${
            activeTab === "cron_jobs"
              ? "bg-zinc-800 text-white font-semibold shadow-sm"
              : "text-zinc-400 hover:text-zinc-200 hover:bg-zinc-900"
          }`}
        >
          <Clock className="h-3.5 w-3.5 text-blue-400" />
          <span>Background Jobs & Cron ({history.length})</span>
        </button>
        <button
          onClick={() => setActiveTab("audit")}
          className={`px-3.5 py-1.5 rounded-lg text-xs font-medium transition-colors flex items-center gap-2 ${
            activeTab === "audit"
              ? "bg-zinc-800 text-white font-semibold shadow-sm"
              : "text-zinc-400 hover:text-zinc-200 hover:bg-zinc-900"
          }`}
        >
          <FileText className="h-3.5 w-3.5 text-emerald-400" />
          <span>Published Articles ({recentBlogs.length})</span>
        </button>
      </div>

      {/* TAB 1: RSS FEED & ONE-CLICK AI GENERATOR */}
      {activeTab === "rss_ai" && (
        <div className="space-y-6">
          {/* Custom Topic Generator Card */}
          <Card className="bg-zinc-900/60 border-zinc-800">
            <CardHeader className="p-4 pb-2">
              <CardTitle className="text-sm font-semibold text-white flex items-center gap-2">
                <Sparkles className="h-4 w-4 text-indigo-400" />
                Custom AI Article Generator
              </CardTitle>
              <CardDescription className="text-xs text-zinc-400">
                Generate in-depth journalism on any esports topic or tournament match using Gemini 2.5 Flash.
              </CardDescription>
            </CardHeader>
            <CardContent className="p-4 pt-2 space-y-4">
              <div className="grid grid-cols-1 md:grid-cols-4 gap-3">
                <div className="md:col-span-3 space-y-1">
                  <label className="text-[11px] font-mono text-zinc-400">Headline / Topic</label>
                  <Input
                    value={customTopic}
                    onChange={(e) => setCustomTopic(e.target.value)}
                    placeholder="e.g. Sentinels Triumph Over Fnatic in Masters Bangkok Lower Final"
                    className="bg-zinc-950 border-zinc-800 text-xs text-white"
                  />
                </div>
                <div className="space-y-1">
                  <label className="text-[11px] font-mono text-zinc-400">Category</label>
                  <select
                    value={selectedCategory}
                    onChange={(e) => setSelectedCategory(e.target.value)}
                    className="w-full h-9 rounded-md bg-zinc-950 border border-zinc-800 px-3 text-xs text-white"
                  >
                    <option value="news">News</option>
                    <option value="analysis">Tactical Analysis</option>
                    <option value="guide">Guide</option>
                    <option value="preview">Tournament Preview</option>
                    <option value="opinion">Editorial Opinion</option>
                  </select>
                </div>
              </div>

              <div className="flex items-center justify-between pt-1">
                <div className="flex items-center gap-2">
                  <button
                    type="button"
                    onClick={() => setAutoPublish(!autoPublish)}
                    className={`h-4 w-4 rounded border flex items-center justify-center transition-colors ${
                      autoPublish ? "bg-indigo-600 border-indigo-500" : "border-zinc-700 bg-zinc-950"
                    }`}
                  >
                    {autoPublish && <Check className="h-3 w-3 text-white" />}
                  </button>
                  <span className="text-xs text-zinc-400">
                    Publish immediately to live site (Skip preview)
                  </span>
                </div>

                <Button
                  onClick={handleGenerateCustom}
                  disabled={isGenerating || isPending}
                  className="bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-semibold gap-1.5"
                >
                  <Sparkles className={`h-3.5 w-3.5 ${isGenerating ? "animate-spin" : ""}`} />
                  {isGenerating ? "Synthesizing with Gemini..." : "Generate Article Draft"}
                </Button>
              </div>
            </CardContent>
          </Card>

          {/* VLR.gg RSS Feed List */}
          <div className="space-y-3">
            <div className="flex items-center justify-between">
              <div>
                <h2 className="text-sm font-semibold text-white">Live VLR.gg Ingestion Feed</h2>
                <p className="text-xs text-zinc-400">
                  Real-time esports news stream. Select any story to synthesize with Gemini.
                </p>
              </div>
              <Button
                variant="outline"
                size="sm"
                onClick={() => handleTestApi("rss")}
                disabled={apiTesting.rss}
                className="text-xs border-zinc-700 bg-zinc-900 gap-1.5"
              >
                <RefreshCw className={`h-3 w-3 ${apiTesting.rss ? "animate-spin" : ""}`} />
                Fetch Latest
              </Button>
            </div>

            <div className="space-y-2.5">
              {rssItems.length === 0 ? (
                <div className="p-8 text-center text-xs text-zinc-500 border border-zinc-800 rounded-xl bg-zinc-900/40">
                  No RSS items available or feed currently loading.
                </div>
              ) : (
                rssItems.map((item, idx) => (
                  <div
                    key={idx}
                    className="p-4 rounded-xl border border-zinc-800 bg-zinc-900/60 hover:bg-zinc-900/90 transition-all flex flex-col sm:flex-row sm:items-center justify-between gap-3"
                  >
                    <div className="space-y-1 max-w-2xl">
                      <div className="flex items-center gap-2">
                        <span className="font-semibold text-xs text-white hover:text-indigo-400 transition-colors">
                          {item.title}
                        </span>
                        {item.isCovered ? (
                          <Badge variant="outline" className="bg-emerald-500/10 text-emerald-400 border-emerald-500/20 text-[9px]">
                            <Check className="h-2.5 w-2.5 mr-0.5" /> Covered in DB
                          </Badge>
                        ) : (
                          <Badge variant="outline" className="bg-amber-500/10 text-amber-400 border-amber-500/20 text-[9px]">
                            New Story
                          </Badge>
                        )}
                      </div>
                      <p className="text-[11px] text-zinc-400 line-clamp-1">
                        {item.contentSnippet || "Verified competitive tactical shooter reporting."}
                      </p>
                      <div className="flex items-center gap-3 text-[10px] text-zinc-500 font-mono">
                        <span>{item.pubDate}</span>
                        <a
                          href={item.link}
                          target="_blank"
                          rel="noreferrer"
                          className="text-indigo-400 hover:underline flex items-center gap-0.5"
                        >
                          Source <ExternalLink className="h-2.5 w-2.5" />
                        </a>
                      </div>
                    </div>

                    <Button
                      size="sm"
                      onClick={() => handleGenerateFromRss(item)}
                      disabled={isGenerating || isPending}
                      className="shrink-0 bg-zinc-800 hover:bg-indigo-600 text-zinc-200 hover:text-white text-xs gap-1.5 transition-colors border border-zinc-700"
                    >
                      <Sparkles className="h-3 w-3 text-indigo-400" />
                      Synthesize Article
                    </Button>
                  </div>
                ))
              )}
            </div>
          </div>
        </div>
      )}

      {/* TAB 2: PANDASCORE MATCH SYNC */}
      {activeTab === "pandascore" && (
        <div className="space-y-6">
          <Card className="bg-zinc-900/60 border-zinc-800">
            <CardHeader className="p-4 pb-2">
              <CardTitle className="text-sm font-semibold text-white flex items-center gap-2">
                <Gamepad2 className="h-4 w-4 text-amber-400" />
                PandaScore Official Ingestion Engine
              </CardTitle>
              <CardDescription className="text-xs text-zinc-400">
                Polls live match results, tournament brackets, and team rosters directly from the PandaScore REST API.
              </CardDescription>
            </CardHeader>
            <CardContent className="p-4 pt-2 space-y-4">
              <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
                <div className="space-y-1">
                  <label className="text-[11px] font-mono text-zinc-400">Select Game Title</label>
                  <select
                    value={selectedGame}
                    onChange={(e) => setSelectedGame(e.target.value)}
                    className="w-full h-9 rounded-md bg-zinc-950 border border-zinc-800 px-3 text-xs text-white"
                  >
                    <option value="valorant">Valorant</option>
                    <option value="cs2">Counter-Strike 2 (CS2)</option>
                    <option value="lol">League of Legends</option>
                    <option value="dota-2">Dota 2</option>
                    <option value="pubg-mobile">PUBG Mobile / BGMI</option>
                  </select>
                </div>

                <div className="space-y-1">
                  <label className="text-[11px] font-mono text-zinc-400">Max Matches to Fetch</label>
                  <select
                    value={syncLimit}
                    onChange={(e) => setSyncLimit(e.target.value)}
                    className="w-full h-9 rounded-md bg-zinc-950 border border-zinc-800 px-3 text-xs text-white"
                  >
                    <option value="5">5 Matches</option>
                    <option value="10">10 Matches</option>
                    <option value="25">25 Matches (Max per batch)</option>
                  </select>
                </div>

                <div className="space-y-1">
                  <label className="text-[11px] font-mono text-zinc-400">Execution Mode</label>
                  <div className="flex items-center gap-2 h-9 px-3 rounded-md bg-zinc-950 border border-zinc-800">
                    <button
                      type="button"
                      onClick={() => setDryRun(!dryRun)}
                      className={`h-4 w-4 rounded border flex items-center justify-center transition-colors ${
                        dryRun ? "bg-amber-600 border-amber-500" : "border-zinc-700 bg-zinc-900"
                      }`}
                    >
                      {dryRun && <Check className="h-3 w-3 text-white" />}
                    </button>
                    <span className="text-xs text-zinc-300">
                      {dryRun ? "Dry Run (Safety Simulation)" : "Live Database Sync"}
                    </span>
                  </div>
                </div>
              </div>

              <div className="p-3 rounded-lg bg-zinc-950 border border-zinc-800 text-[11px] text-zinc-400 space-y-1">
                <div className="flex items-center gap-1.5 text-emerald-400 font-semibold">
                  <ShieldCheck className="h-3.5 w-3.5" />
                  <span>Idempotent Upsert Safeguard Active</span>
                </div>
                <p>
                  Matches are evaluated by external ID. Existing matches are updated with final scores; new matches are staged safely without breaking foreign keys or creating duplicate rows.
                </p>
              </div>

              <div className="flex justify-end">
                <Button
                  onClick={handleRunPandaScore}
                  disabled={isPending}
                  className="bg-amber-600 hover:bg-amber-500 text-white text-xs font-semibold gap-1.5"
                >
                  <RefreshCw className={`h-3.5 w-3.5 ${isPending ? "animate-spin" : ""}`} />
                  {dryRun ? "Run PandaScore Dry-Run" : "Execute Live Sync"}
                </Button>
              </div>
            </CardContent>
          </Card>

          {/* Sync Result Card */}
          {syncResult && (
            <Card className="bg-zinc-900/60 border-zinc-800">
              <CardHeader className="p-4 pb-2">
                <CardTitle className="text-sm font-semibold text-white flex items-center justify-between">
                  <span>Sync Result Summary</span>
                  <Badge variant="outline" className="bg-emerald-500/10 text-emerald-400 border-emerald-500/20 text-[10px]">
                    {syncResult.matchesCount} Matches Processed ({syncResult.durationMs}ms)
                  </Badge>
                </CardTitle>
              </CardHeader>
              <CardContent className="p-4 pt-2">
                <div className="space-y-2">
                  {(syncResult.sample || []).map((m, i) => (
                    <div
                      key={i}
                      className="p-2.5 rounded bg-zinc-950 border border-zinc-800 flex items-center justify-between text-xs"
                    >
                      <div>
                        <span className="font-semibold text-white">{m.name || "Esports Match"}</span>
                        <div className="text-[10px] text-zinc-500 font-mono">
                          {m.league || "Tournament"} • Status: {m.status}
                        </div>
                      </div>
                      <span className="text-[11px] font-mono text-zinc-400">{m.begin_at?.slice(0, 10)}</span>
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>
          )}
        </div>
      )}

      {/* TAB 3: BACKGROUND JOBS & CRON MONITOR */}
      {activeTab === "cron_jobs" && (
        <div className="space-y-6">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <Card className="bg-zinc-900/60 border-zinc-800">
              <CardHeader className="p-4 pb-2">
                <span className="text-[11px] font-mono uppercase text-zinc-400">Job: AI Article Generator</span>
                <CardTitle className="text-sm font-semibold text-white flex items-center justify-between">
                  <span>Hourly Ingestion</span>
                  <Badge variant="outline" className="bg-emerald-500/10 text-emerald-400 border-emerald-500/20 text-[9px]">
                    Active
                  </Badge>
                </CardTitle>
              </CardHeader>
              <CardContent className="p-4 pt-1 text-xs text-zinc-400 space-y-2">
                <p>Fetches VLR.gg RSS, selects un-covered stories, synthesizes article with Gemini, alerts Discord.</p>
                <div className="text-[10px] font-mono text-zinc-500">Schedule: 0 * * * * (Hourly)</div>
              </CardContent>
            </Card>

            <Card className="bg-zinc-900/60 border-zinc-800">
              <CardHeader className="p-4 pb-2">
                <span className="text-[11px] font-mono uppercase text-zinc-400">Job: Live Score Sync</span>
                <CardTitle className="text-sm font-semibold text-white flex items-center justify-between">
                  <span>Match Poller</span>
                  <Badge variant="outline" className="bg-emerald-500/10 text-emerald-400 border-emerald-500/20 text-[9px]">
                    Active
                  </Badge>
                </CardTitle>
              </CardHeader>
              <CardContent className="p-4 pt-1 text-xs text-zinc-400 space-y-2">
                <p>Polls PandaScore for live status updates, maps scores, and updates winner IDs.</p>
                <div className="text-[10px] font-mono text-zinc-500">Schedule: */15 * * * * (15 mins)</div>
              </CardContent>
            </Card>

            <Card className="bg-zinc-900/60 border-zinc-800">
              <CardHeader className="p-4 pb-2">
                <span className="text-[11px] font-mono uppercase text-zinc-400">Job: Sitemap Re-index</span>
                <CardTitle className="text-sm font-semibold text-white flex items-center justify-between">
                  <span>Sitemap Cache</span>
                  <Badge variant="outline" className="bg-blue-500/10 text-blue-400 border-blue-500/20 text-[9px]">
                    Scheduled
                  </Badge>
                </CardTitle>
              </CardHeader>
              <CardContent className="p-4 pt-1 text-xs text-zinc-400 space-y-2">
                <p>Refreshes XML sitemap indexes (matches, tournaments, players, teams, articles).</p>
                <div className="text-[10px] font-mono text-zinc-500">Schedule: 0 3 * * * (Nightly 3 AM)</div>
              </CardContent>
            </Card>
          </div>

          {/* Execution History Table */}
          <div className="space-y-3">
            <div className="flex items-center justify-between">
              <div>
                <h3 className="text-sm font-semibold text-white">Recent Execution History</h3>
                <p className="text-xs text-zinc-400">
                  Logs of automated cron and manual pipeline trigger events.
                </p>
              </div>
              <Button
                variant="outline"
                size="sm"
                onClick={handleTriggerCron}
                disabled={isPending}
                className="text-xs border-zinc-700 bg-zinc-900 gap-1.5"
              >
                <Play className="h-3 w-3" />
                Run Cron Trigger
              </Button>
            </div>

            <div className="overflow-x-auto rounded-xl border border-zinc-800 bg-zinc-900/60 shadow-xl">
              <table className="w-full text-left text-xs">
                <thead className="bg-zinc-950/80 text-[10px] uppercase font-mono tracking-wider text-zinc-400 border-b border-zinc-800">
                  <tr>
                    <th className="py-3 px-4">Job Execution</th>
                    <th className="py-3 px-4">Status</th>
                    <th className="py-3 px-4">Duration</th>
                    <th className="py-3 px-4">Timestamp</th>
                    <th className="py-3 px-4">Summary</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-zinc-800/60 text-zinc-300">
                  {history.map((job) => (
                    <tr key={job.id} className="hover:bg-zinc-800/40 transition-colors">
                      <td className="py-3 px-4">
                        <div className="font-semibold text-white">{job.name}</div>
                        <div className="text-[10px] text-zinc-500 font-mono">ID: {job.id}</div>
                      </td>
                      <td className="py-3 px-4">
                        <Badge
                          variant="outline"
                          className={`text-[9px] font-mono ${
                            job.status === "success"
                              ? "bg-emerald-500/10 text-emerald-400 border-emerald-500/20"
                              : job.status === "skipped"
                              ? "bg-amber-500/10 text-amber-400 border-amber-500/20"
                              : "bg-red-500/10 text-red-400 border-red-500/20"
                          }`}
                        >
                          {job.status.toUpperCase()}
                        </Badge>
                      </td>
                      <td className="py-3 px-4 font-mono text-zinc-400">
                        {job.durationMs ? `${job.durationMs}ms` : "—"}
                      </td>
                      <td className="py-3 px-4 font-mono text-[11px] text-zinc-400">
                        {job.timestamp ? new Date(job.timestamp).toLocaleTimeString() : "—"}
                      </td>
                      <td className="py-3 px-4 text-zinc-300 text-[11px] max-w-md truncate">
                        {job.details}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      )}

      {/* TAB 4: PUBLISHED ARTICLES AUDIT */}
      {activeTab === "audit" && (
        <div className="space-y-4">
          <div className="flex items-center justify-between">
            <div>
              <h2 className="text-sm font-semibold text-white">Live Editorial Database Articles</h2>
              <p className="text-xs text-zinc-400">
                Recently published articles generated by AI or edited by the administrative team.
              </p>
            </div>
            <Button asChild size="sm" variant="outline" className="text-xs border-zinc-700 bg-zinc-900 gap-1.5">
              <Link href="/blogs">
                Full Blog Management <ArrowRight className="h-3 w-3" />
              </Link>
            </Button>
          </div>

          <div className="space-y-2.5">
            {recentBlogs.map((b) => (
              <div
                key={b.id}
                className="p-4 rounded-xl border border-zinc-800 bg-zinc-900/60 hover:bg-zinc-900/90 transition-all flex flex-col sm:flex-row sm:items-center justify-between gap-3"
              >
                <div className="space-y-1 max-w-2xl">
                  <div className="flex items-center gap-2">
                    <span className="font-semibold text-xs text-white">{b.title}</span>
                    <Badge variant="outline" className="bg-emerald-500/10 text-emerald-400 border-emerald-500/20 text-[9px]">
                      Live
                    </Badge>
                  </div>
                  <p className="text-[11px] text-zinc-400 line-clamp-1">{b.excerpt}</p>
                  <div className="flex items-center gap-3 text-[10px] text-zinc-500 font-mono">
                    <span>Published: {new Date(b.created_at).toLocaleDateString()}</span>
                    <span>Slug: /blogs/{b.slug}</span>
                  </div>
                </div>

                <div className="flex items-center gap-2 shrink-0">
                  <Button asChild size="sm" variant="ghost" className="h-7 text-xs text-zinc-400 hover:text-white">
                    <Link href={`/blogs/edit/${b.id}`}>Edit</Link>
                  </Button>
                  <Button asChild size="sm" variant="outline" className="h-7 text-xs border-zinc-700 bg-zinc-800 gap-1">
                    <a href={`https://khelpedia.org/blogs/${b.slug}`} target="_blank" rel="noreferrer">
                      View Live <ExternalLink className="h-3 w-3" />
                    </a>
                  </Button>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* DRAFT REVIEW & PUBLISH MODAL */}
      {draftModal && (
        <div className="fixed inset-0 z-50 bg-black/80 backdrop-blur-sm flex items-center justify-center p-4">
          <div className="bg-zinc-900 border border-zinc-800 rounded-xl max-w-3xl w-full p-6 shadow-2xl space-y-4 max-h-[90vh] overflow-y-auto">
            <div className="flex items-center justify-between border-b border-zinc-800 pb-3">
              <div className="flex items-center gap-2">
                <Sparkles className="h-4 w-4 text-indigo-400" />
                <h3 className="font-semibold text-white text-sm">
                  Review Gemini-Generated Article Draft
                </h3>
              </div>
              <button
                onClick={() => setDraftModal(null)}
                className="text-zinc-400 hover:text-white p-1 rounded"
              >
                <X className="h-4 w-4" />
              </button>
            </div>

            <div className="space-y-4 text-xs">
              <div className="space-y-1">
                <label className="text-[11px] font-mono text-zinc-400">Headline</label>
                <Input
                  value={draftModal.title}
                  onChange={(e) => setDraftModal({ ...draftModal, title: e.target.value })}
                  className="bg-zinc-950 border-zinc-800 text-xs text-white font-semibold"
                />
              </div>

              <div className="space-y-1">
                <label className="text-[11px] font-mono text-zinc-400">Excerpt / Meta Description</label>
                <textarea
                  value={draftModal.excerpt}
                  onChange={(e) => setDraftModal({ ...draftModal, excerpt: e.target.value })}
                  rows={2}
                  className="w-full rounded-md bg-zinc-950 border border-zinc-800 p-2.5 text-xs text-zinc-300"
                />
              </div>

              <div className="space-y-1">
                <label className="text-[11px] font-mono text-zinc-400">
                  Article Body (HTML Preview)
                </label>
                <div
                  className="p-4 rounded-lg bg-zinc-950 border border-zinc-800 text-zinc-300 prose prose-invert prose-xs max-h-64 overflow-y-auto"
                  dangerouslySetInnerHTML={{ __html: draftModal.content }}
                />
              </div>
            </div>

            <div className="flex items-center justify-between pt-3 border-t border-zinc-800">
              <span className="text-[11px] font-mono text-zinc-500">
                Target URL: /blogs/{draftModal.slug}
              </span>
              <div className="flex items-center gap-2">
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={() => setDraftModal(null)}
                  className="text-xs text-zinc-400 hover:text-white"
                >
                  Discard Draft
                </Button>
                <Button
                  size="sm"
                  onClick={handlePublishDraft}
                  disabled={isPending}
                  className="bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-semibold gap-1.5"
                >
                  <Check className="h-3.5 w-3.5" />
                  Publish Live to KhelPediA
                </Button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
